### ISSUE TITLE
Role needs updating

### ISSUE THREAD

**Issue by francisco1844** [dochang/ansible-role-account#2]
~/hg/natserv-ansible/ricambi$ansible-galaxy install dochang.account
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list of hosts, a directory or a list of paths . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of become which is a generic framework . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a generic framework . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
- downloading role 'account', owned by dochang
- downloading role from https://github.com/dochang/ansible-role-account/archive/master.tar.gz
- extracting dochang.account to /etc/ansible/roles/dochang.account
- extracting dochang.account to /home/francisco/natserv-ansible/ricambi/roles/dochang.account
- dochang.account (master) was installed successfully

**Comment by dochang** [comment]
These warnings comes from Ansible configuration.  Please check your `ansible.cfg`, command line arguments and environment variables.

**Comment by francisco1844** [comment]
Thanks.
Removed all calls to sudo and changed hostfile to inventory in ansible.cfg. That did the trick.
